### ISSUE TITLE
Could not find a version that satisfies the requirement nose==0.11.3?

### ISSUE THREAD

**Issue by litt1e-p** [listen1/listen1#10]
it shows an error: "Could not find a version that satisfies the requirement nose==0.11.3" when execute command "pip install -r requirements/dev.txt". did I did it wrong?

**Comment by listen1** [comment]
sorry, those deprecated libs are generated by boil plate. You can delete nose and fabric lib in requirements/dev.txt. I will update the file. 
thanks for reporting.

**Comment by litt1e-p** [comment]
OK, thanks.
