### ISSUE TITLE
QQ音乐无法播放了

### ISSUE THREAD

**Issue by linchanx** [listen1/listen1#28]
QQ音乐无法播放了，具体就是点了没反应，但是firefox标签页有播放的图标，网易和虾米没问题。

**Comment by linchanx** [comment]
抱歉，是我网络问题，已修复。

**Comment by RaoXiaoMan** [comment]
相同问题 麻烦介绍下 你是怎么解决的

**Comment by linchanx** [comment]
我是网络问题。换了一个dns就好了。

太阳星星万物都听我的指挥 <notifications@github.com>于2017年9月19日周二 下午2:54写道：
