### ISSUE TITLE
nice work, check out my backend

### ISSUE THREAD

**Issue by LIU9293** [listen1/listen1#44]
差不多一年前我做了一个[类似的项目](https://github.com/LIU9293/musicAPI)
我大概看了一下backend的API，好像没我的全，你可以去我的项目底下点一点测试链接
最近正好想重构原来的代码，有兴趣的话可以讨论讨论

**Comment by listen1** [comment]
非常好的项目，特别是api确实很全。欢迎gmail交流。邮件地址见github资料。
