### ISSUE TITLE
首页的Linux下载获取的已不是dab安装包而是AppImage包，请修改主页上的Linux版安装说明

### ISSUE THREAD

**Issue by eonun** [listen1/listen1#61]
首页的Linux下载获取的已不是`dab`安装包而是`AppImage`包，请修改主页上的Linux版安装说明，并指明需要给`AppImage`包执行权限

**Comment by listen1** [comment]
好的，感谢你的反馈，已经修改了说明

**Comment by eonun** [comment]
AppImage包需要给执行权限方可运行，第2点出现了错别字(^-^;)
> 2.点击下载的按照包，在安装界面点击Install

建议改成这样：

1. 根据系统选择32位或64位版本，下载AppImage安装包
2. 将安装包放到合适的位置，右键安装包>属性>权限>赋予执行权限，或在命令行使用chmod a+x赋予执行权限，然后就可直接双击运行软件，弹出是否将软件集成到程序菜单中的窗口，同意或不同意都可运行软件，建议同意
3. 如果需要debian安装包，请访问 [此链接](https://github.com/listen1/listen1_desktop/releases)

**Comment by listen1** [comment]
已经修改了相关说明，谢谢，以后要更仔细的更新了

**Comment by RebelYoung** [comment]
你好，appimage执行后没有弹出 集成到程序菜单窗口，这怎么办呀？
