### ISSUE TITLE
MAC Inter版本无法播放

### ISSUE THREAD

**Issue by hcl666** [listen1/listen1#81]
![image](https://user-images.githubusercontent.com/28346798/118491137-42730400-b751-11eb-8a10-17d672c045f9.png)
软件版本2.21.4 (2.21.4)

**Comment by listen1** [comment]
麻烦能按F12打开调试页面，看一下console标签页下有没有报错信息吗？谢谢

**Comment by hcl666** [comment]
不好意思，已经卸载了
